"use client"

import { useState } from "react"
import { Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Copy, Download, Share2, FileJson, FileText, CheckCircle2, Loader2 } from "lucide-react"
import { Badge } from "@/components/ui/badge"

interface ExportShareProps {
  analysisId: string
  analysisData: any
}

export function ExportSharePanel({ analysisId, analysisData }: ExportShareProps) {
  const [shareLink, setShareLink] = useState<string | null>(null)
  const [copied, setCopied] = useState(false)
  const [loading, setLoading] = useState(false)
  const [exporting, setExporting] = useState<string | null>(null)

  const generateShareLink = async () => {
    setLoading(true)
    try {
      const API = process.env.NEXT_PUBLIC_API_URL;
      const response = await fetch(`${API}/api/share`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ analysisId, expiresIn: 10080 }), // 7 days
      })

      if (!response.ok) {
        throw new Error("Failed to generate share link")
      }

      const data = await response.json()
      setShareLink(data.shareUrl || `${window.location.origin}/share/${data.shareToken}`)
    } catch (error: any) {
      console.error("Failed to generate share link:", error)
      alert(error.message || "Failed to generate share link. Please try again.")
    } finally {
      setLoading(false)
    }
  }

  const copyShareLink = () => {
    if (shareLink) {
      navigator.clipboard.writeText(shareLink)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }
  }

  const exportAsJSON = () => {
    setExporting("json")
    try {
      const dataStr = JSON.stringify(analysisData, null, 2)
      const dataBlob = new Blob([dataStr], { type: "application/json" })
      const url = URL.createObjectURL(dataBlob)
      const link = document.createElement("a")
      link.href = url
      link.download = `analysis-${analysisId}.json`
      link.click()
      URL.revokeObjectURL(url)
      setTimeout(() => setExporting(null), 1000)
    } catch (error) {
      console.error("Failed to export JSON:", error)
      setExporting(null)
    }
  }

  const exportAsMarkdown = () => {
    setExporting("markdown")
    try {
      const md = `# Code Analysis Report

## Original Code
\`\`\`${analysisData.language || "text"}
${analysisData.originalCode || "N/A"}
\`\`\`

## Analysis

### Explanation
${analysisData.explanation || "N/A"}

### Bugs Detected
${analysisData.bugsDetected?.map((b: any) => `- **Line ${b.line}**: ${b.issue} (${b.severity})`).join("\n") || "No bugs detected"}

### Suggested Fixes
${analysisData.suggestedFixes || "N/A"}

### Optimized Code
\`\`\`${analysisData.language || "text"}
${analysisData.optimizedCode || "N/A"}
\`\`\`

### Execution Results
- **Output**: ${analysisData.output || "N/A"}
- **Error**: ${analysisData.error || "None"}
- **Execution Time**: ${analysisData.executionTime || 0}ms

---
*Generated by CodeMind AI Code Analysis*
`

      const dataBlob = new Blob([md], { type: "text/markdown" })
      const url = URL.createObjectURL(dataBlob)
      const link = document.createElement("a")
      link.href = url
      link.download = `analysis-${analysisId}.md`
      link.click()
      URL.revokeObjectURL(url)
      setTimeout(() => setExporting(null), 1000)
    } catch (error) {
      console.error("Failed to export Markdown:", error)
      setExporting(null)
    }
  }

  return (
    <div className="space-y-4 animate-in fade-in duration-300">
      {/* Share Section */}
      <Card className="p-4 bg-card/50 border-accent/20 hover:border-accent/40 transition-all duration-200">
        <h3 className="text-sm font-semibold mb-3 flex items-center gap-2 text-foreground">
          <Share2 className="w-4 h-4 text-accent" />
          Share Analysis
        </h3>

        <Button
          onClick={generateShareLink}
          disabled={loading}
          className="w-full mb-3 bg-gradient-to-r from-accent to-primary hover:from-accent/90 hover:to-primary/90 text-accent-foreground transition-all duration-200 hover:scale-105 disabled:opacity-50"
        >
          {loading ? (
            <>
              <Loader2 className="w-4 h-4 mr-2 animate-spin" />
              Generating...
            </>
          ) : (
            <>
              <Share2 className="w-4 h-4 mr-2" />
              Generate Share Link
            </>
          )}
        </Button>

        {shareLink && (
          <div className="space-y-2 animate-in fade-in slide-in-from-top duration-300">
            <div className="p-3 bg-background/50 rounded-lg border border-border/50 flex items-center justify-between gap-2">
              <span className="text-xs text-muted-foreground truncate flex-1">{shareLink}</span>
              <Button
                size="sm"
                variant="ghost"
                className="h-7 w-7 p-0 hover:bg-accent/10 transition-all duration-200"
                onClick={copyShareLink}
              >
                {copied ? (
                  <CheckCircle2 className="w-3.5 h-3.5 text-accent" />
                ) : (
                  <Copy className="w-3.5 h-3.5" />
                )}
              </Button>
            </div>
            <div className="flex items-center justify-between">
              <p className="text-xs text-muted-foreground">Link expires in 7 days</p>
              {copied && (
                <Badge variant="outline" className="text-xs bg-accent/10 border-accent/30 text-accent animate-in fade-in">
                  Copied!
                </Badge>
              )}
            </div>
          </div>
        )}
      </Card>

      {/* Export Section */}
      <Card className="p-4 bg-card/50 border-border hover:border-accent/30 transition-all duration-200">
        <h3 className="text-sm font-semibold mb-3 flex items-center gap-2 text-foreground">
          <Download className="w-4 h-4 text-accent" />
          Export Analysis
        </h3>

        <div className="space-y-2">
          <Button
            onClick={exportAsJSON}
            disabled={exporting === "json"}
            className="w-full justify-start gap-2 h-10 bg-primary hover:bg-primary/90 text-primary-foreground transition-all duration-200 hover:scale-105 disabled:opacity-50"
          >
            {exporting === "json" ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                Exporting...
              </>
            ) : (
              <>
                <FileJson className="w-4 h-4" />
                Export as JSON
              </>
            )}
          </Button>

          <Button
            onClick={exportAsMarkdown}
            disabled={exporting === "markdown"}
            className="w-full justify-start gap-2 h-10 bg-secondary hover:bg-secondary/90 text-secondary-foreground transition-all duration-200 hover:scale-105 disabled:opacity-50"
          >
            {exporting === "markdown" ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                Exporting...
              </>
            ) : (
              <>
                <FileText className="w-4 h-4" />
                Export as Markdown
              </>
            )}
          </Button>
        </div>
      </Card>

      {/* Format Info */}
      <Card className="p-4 bg-background/50 border-border/50 animate-in fade-in duration-300">
        <p className="text-xs text-muted-foreground leading-relaxed">
          <span className="font-semibold text-foreground">💡 Tip:</span> Share links allow others to view your analysis
          without access to your account. Markdown is great for documentation and reports, while JSON is perfect for
          programmatic use.
        </p>
      </Card>
    </div>
  )
}
